//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailon_Manasco_Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int DrugId { get; set; }
        public string Name { get; set; }
        public decimal UnitPrice { get; set; }
        public int QoH { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
