//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailon_Manasco_Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderLineId { get; set; }
        public int DrugId { get; set; }
        public int OrderId { get; set; }
        public short Quantity { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Order Order { get; set; }
    }
}
